import type { IngredientCategoryKey } from '../constants/ingredientCategories'

export interface CommonShoppingIngredient {
  name: string
  category: IngredientCategoryKey
}

/**
 * Curated supermarket staples for manual shopping-list entry (autocomplete only).
 * Names are German, categories match persisted recipe ingredient keys.
 */
export const COMMON_SHOPPING_INGREDIENTS: CommonShoppingIngredient[] = [
  // Obst & Gemüse
  { name: 'Tomaten', category: 'produce' },
  { name: 'Kirschtomaten', category: 'produce' },
  { name: 'Rispentomaten', category: 'produce' },
  { name: 'Cherrytomaten', category: 'produce' },
  { name: 'Cocktailtomaten', category: 'produce' },
  { name: 'Zwiebeln', category: 'produce' },
  { name: 'Rote Zwiebeln', category: 'produce' },
  { name: 'Schalotten', category: 'produce' },
  { name: 'Knoblauch', category: 'produce' },
  { name: 'Kartoffeln', category: 'produce' },
  { name: 'Süßkartoffeln', category: 'produce' },
  { name: 'Karotten', category: 'produce' },
  { name: 'Möhren', category: 'produce' },
  { name: 'Paprika', category: 'produce' },
  { name: 'Gurken', category: 'produce' },
  { name: 'Zucchini', category: 'produce' },
  { name: 'Auberginen', category: 'produce' },
  { name: 'Brokkoli', category: 'produce' },
  { name: 'Brokkoliröschen', category: 'produce' },
  { name: 'Blumenkohl', category: 'produce' },
  { name: 'Blumenkohlröschen', category: 'produce' },
  { name: 'Spinat', category: 'produce' },
  { name: 'Babyspinat', category: 'produce' },
  { name: 'Salat', category: 'produce' },
  { name: 'Feldsalat', category: 'produce' },
  { name: 'Eisbergsalat', category: 'produce' },
  { name: 'Romana-Salat', category: 'produce' },
  { name: 'Rucola', category: 'produce' },
  { name: 'Champignons', category: 'produce' },
  { name: 'Weiße Champignons', category: 'produce' },
  { name: 'Braune Champignons', category: 'produce' },
  { name: 'Lauch', category: 'produce' },
  { name: 'Lauchzwiebeln', category: 'produce' },
  { name: 'Frühlingszwiebeln', category: 'produce' },
  { name: 'Sellerie', category: 'produce' },
  { name: 'Knollensellerie', category: 'produce' },
  { name: 'Limetten', category: 'produce' },
  { name: 'Zitronen', category: 'produce' },
  { name: 'Äpfel', category: 'produce' },
  { name: 'Bananen', category: 'produce' },
  { name: 'Avocado', category: 'produce' },
  { name: 'schwarze Oliven', category: 'produce' },
  { name: 'Ingwer', category: 'produce' },
  { name: 'Petersilie', category: 'produce' },
  { name: 'Basilikum', category: 'produce' },
  { name: 'Koriander', category: 'produce' },
  { name: 'Dill', category: 'produce' },
  { name: 'Schnittlauch', category: 'produce' },
  { name: 'Thymian', category: 'produce' },
  { name: 'Rosmarin', category: 'produce' },
  { name: 'Minze', category: 'produce' },
  { name: 'Spargel', category: 'produce' },
  { name: 'Erbsen', category: 'produce' },
  { name: 'Grüne Bohnen', category: 'produce' },
  { name: 'Zuckermais', category: 'produce' },
  { name: 'Kürbis', category: 'produce' },
  { name: 'Hokkaido-Kürbis', category: 'produce' },
  { name: 'Butternut-Kürbis', category: 'produce' },
  { name: 'Fenchel', category: 'produce' },
  { name: 'Rote Bete', category: 'produce' },
  { name: 'Kohlrabi', category: 'produce' },
  { name: 'Weißkohl', category: 'produce' },
  { name: 'Rotkohl', category: 'produce' },
  { name: 'Rosenkohl', category: 'produce' },
  { name: 'Pak Choi', category: 'produce' },
  { name: 'Grünkohl', category: 'produce' },
  { name: 'Mangold', category: 'produce' },
  { name: 'Radieschen', category: 'produce' },
  { name: 'Pilze', category: 'produce' },
  { name: 'Kräuterseitlinge', category: 'produce' },
  { name: 'Pfifferlinge', category: 'produce' },

  // Gewürze
  { name: 'Salz', category: 'spices' },
  { name: 'Meersalz', category: 'spices' },
  { name: 'Pfeffer', category: 'spices' },
  { name: 'Paprikapulver', category: 'spices' },
  { name: 'Curry', category: 'spices' },
  { name: 'Zimt', category: 'spices' },
  { name: 'Chiliflocken', category: 'spices' },
  { name: 'Muskatnuss', category: 'spices' },
  { name: 'Kreuzkümmel', category: 'spices' },
  { name: 'Kurkuma', category: 'spices' },
  { name: 'Ingwerpulver', category: 'spices' },
  { name: 'Knoblauchpulver', category: 'spices' },
  { name: 'Zwiebelpulver', category: 'spices' },
  { name: 'Oregano', category: 'spices' },
  { name: 'Thymian (getrocknet)', category: 'spices' },
  { name: 'Rosmarin (getrocknet)', category: 'spices' },
  { name: 'Kräuter der Provence', category: 'spices' },
  { name: 'Currypulver', category: 'spices' },
  { name: 'Geräuchertes Paprikapulver', category: 'spices' },
  { name: 'Chilipulver', category: 'spices' },
  { name: 'Cayennepfeffer', category: 'spices' },
  { name: 'Sternanis', category: 'spices' },
  { name: 'Nelken', category: 'spices' },

  // Getreide & Beilagen
  { name: 'Reis', category: 'grains' },
  { name: 'Basmatireis', category: 'grains' },
  { name: 'Jasminreis', category: 'grains' },
  { name: 'Vollkornreis', category: 'grains' },
  { name: 'Parboiled Reis', category: 'grains' },
  { name: 'Risotto-Reis', category: 'grains' },
  { name: 'Arborio-Reis', category: 'grains' },
  { name: 'Wildreis', category: 'grains' },
  { name: 'Nudeln', category: 'grains' },
  { name: 'Spaghetti', category: 'grains' },
  { name: 'Penne', category: 'grains' },
  { name: 'Bandnudeln', category: 'grains' },
  { name: 'Vollkornnudeln', category: 'grains' },
  { name: 'Reisnudeln', category: 'grains' },
  { name: 'Fusilli', category: 'grains' },
  { name: 'Farfalle', category: 'grains' },
  { name: 'Lasagneplatten', category: 'grains' },
  { name: 'Gnocchi', category: 'grains' },
  { name: 'Tortellini', category: 'grains' },
  { name: 'Wraps', category: 'grains' },
  { name: 'Tortillas', category: 'grains' },
  { name: 'Couscous', category: 'grains' },
  { name: 'Vollkorn-Couscous', category: 'grains' },
  { name: 'Bulgur', category: 'grains' },
  { name: 'Quinoa', category: 'grains' },
  { name: 'Hirse', category: 'grains' },
  { name: 'Polenta', category: 'grains' },
  { name: 'Haferflocken', category: 'grains' },
  { name: 'Feine Haferflocken', category: 'grains' },
  { name: 'Große Haferflocken', category: 'grains' },
  { name: 'Haferkleie', category: 'grains' },
  { name: 'Linsen', category: 'grains' },
  { name: 'Rote Linsen', category: 'grains' },
  { name: 'Grüne Linsen', category: 'grains' },
  { name: 'Beluga-Linsen', category: 'grains' },
  { name: 'Kichererbsen', category: 'grains' },
  { name: 'Schwarze Bohnen', category: 'grains' },
  { name: 'Kidneybohnen', category: 'grains' },
  { name: 'Weiße Bohnen', category: 'grains' },

  // Backen
  { name: 'Mehl', category: 'baking' },
  { name: 'Vollkornmehl', category: 'baking' },
  { name: 'Dinkelmehl', category: 'baking' },
  { name: 'Zucker', category: 'baking' },
  { name: 'Brauner Zucker', category: 'baking' },
  { name: 'Puderzucker', category: 'baking' },
  { name: 'Vanillezucker', category: 'baking' },
  { name: 'Backpulver', category: 'baking' },
  { name: 'Natron', category: 'baking' },
  { name: 'Trockenhefe', category: 'baking' },
  { name: 'Frischhefe', category: 'baking' },
  { name: 'Hefe', category: 'baking' },
  { name: 'Speisestärke', category: 'baking' },
  { name: 'Kakao', category: 'baking' },
  { name: 'Backkakao', category: 'baking' },
  { name: 'Vanilleextrakt', category: 'baking' },
  { name: 'Vanillepaste', category: 'baking' },
  { name: 'Zartbitterschokolade', category: 'baking' },
  { name: 'Schokostückchen', category: 'baking' },
  { name: 'Kokosraspeln', category: 'baking' },
  { name: 'Kokosflocken', category: 'baking' },
  { name: 'Mandelmehl', category: 'baking' },
  { name: 'Gemahlene Mandeln', category: 'baking' },
  { name: 'Gemahlene Nüsse', category: 'baking' },
  { name: 'Kokosmehl', category: 'baking' },
  { name: 'Backgewürz', category: 'baking' },

  // Öle & Fette
  { name: 'Olivenöl', category: 'oils_fats' },
  { name: 'Rapsöl', category: 'oils_fats' },
  { name: 'Sonnenblumenöl', category: 'oils_fats' },
  { name: 'Kokosöl', category: 'oils_fats' },
  { name: 'Sesamöl', category: 'oils_fats' },
  { name: 'Mandelöl', category: 'oils_fats' },
  { name: 'Ghee', category: 'oils_fats' },
  { name: 'Butterschmalz', category: 'oils_fats' },

  // Soßen & Würzmittel (fertige Würzsaucen, nicht Dosen-/Regal-Tomatenprodukte)
  { name: 'Sojasauce', category: 'sauces' },
  { name: 'Senf', category: 'sauces' },
  { name: 'Dijon-Senf', category: 'sauces' },
  { name: 'Ketchup', category: 'sauces' },
  { name: 'Mayonnaise', category: 'sauces' },
  { name: 'Essig', category: 'sauces' },
  { name: 'Balsamico', category: 'sauces' },
  { name: 'Balsamico-Essig', category: 'sauces' },
  { name: 'Reisessig', category: 'sauces' },
  { name: 'Pesto', category: 'sauces' },
  { name: 'Hummus', category: 'sauces' },
  { name: 'BBQ-Sauce', category: 'sauces' },
  { name: 'Sriracha', category: 'sauces' },
  { name: 'Worcestersauce', category: 'sauces' },
  { name: 'Teriyakisauce', category: 'sauces' },
  { name: 'Chilisauce', category: 'sauces' },
  { name: 'Salsa', category: 'sauces' },
  { name: 'Joghurt-Dressing', category: 'sauces' },

  // Fleisch & Fisch
  { name: 'Hackfleisch', category: 'meat_fish' },
  { name: 'Rinderhack', category: 'meat_fish' },
  { name: 'Gemischtes Hack', category: 'meat_fish' },
  { name: 'Hähnchenbrust', category: 'meat_fish' },
  { name: 'Hähnchenkeulen', category: 'meat_fish' },
  { name: 'Hähnchenschenkel', category: 'meat_fish' },
  { name: 'Hähnchenhack', category: 'meat_fish' },
  { name: 'Rindfleisch', category: 'meat_fish' },
  { name: 'Rinderfilet', category: 'meat_fish' },
  { name: 'Schweineschnitzel', category: 'meat_fish' },
  { name: 'Schweinehack', category: 'meat_fish' },
  { name: 'Bratwurst', category: 'meat_fish' },
  { name: 'Wiener Würstchen', category: 'meat_fish' },
  { name: 'Bockwurst', category: 'meat_fish' },
  { name: 'Cabanossi', category: 'meat_fish' },
  { name: 'Salsiccia', category: 'meat_fish' },
  { name: 'Salami', category: 'meat_fish' },
  { name: 'Schinken', category: 'meat_fish' },
  { name: 'Speck', category: 'meat_fish' },
  { name: 'Bacon', category: 'meat_fish' },
  { name: 'Lachs', category: 'meat_fish' },
  { name: 'Forelle', category: 'meat_fish' },
  { name: 'Kabeljau', category: 'meat_fish' },
  { name: 'Seelachs', category: 'meat_fish' },
  { name: 'Garnelen', category: 'meat_fish' },
  { name: 'Miesmuscheln', category: 'meat_fish' },

  // Milchprodukte & Eier
  { name: 'Milch', category: 'dairy_eggs' },
  { name: 'Butter', category: 'dairy_eggs' },
  { name: 'Margarine', category: 'dairy_eggs' },
  { name: 'Sahne', category: 'dairy_eggs' },
  { name: 'Schmand', category: 'dairy_eggs' },
  { name: 'Joghurt', category: 'dairy_eggs' },
  { name: 'Quark', category: 'dairy_eggs' },
  { name: 'Buttermilch', category: 'dairy_eggs' },
  { name: 'Kefir', category: 'dairy_eggs' },
  { name: 'Crème fraîche', category: 'dairy_eggs' },
  { name: 'Frischkäse', category: 'dairy_eggs' },
  { name: 'Körniger Frischkäse', category: 'dairy_eggs' },
  { name: 'Ricotta', category: 'dairy_eggs' },
  { name: 'Mascarpone', category: 'dairy_eggs' },
  { name: 'Skyr', category: 'dairy_eggs' },
  { name: 'Feta', category: 'dairy_eggs' },
  { name: 'Mozzarella', category: 'dairy_eggs' },
  { name: 'Parmesan', category: 'dairy_eggs' },
  { name: 'Gouda', category: 'dairy_eggs' },
  { name: 'Cheddar', category: 'dairy_eggs' },
  { name: 'Emmentaler', category: 'dairy_eggs' },
  { name: 'Ziegenkäse', category: 'dairy_eggs' },
  { name: 'Halloumi', category: 'dairy_eggs' },
  { name: 'Käse', category: 'dairy_eggs' },
  { name: 'Eier', category: 'dairy_eggs' },

  // Getränke
  { name: 'Wasser', category: 'beverages' },
  { name: 'Mineralwasser', category: 'beverages' },
  { name: 'Apfelsaft', category: 'beverages' },
  { name: 'Orangensaft', category: 'beverages' },
  { name: 'Zitronensaft', category: 'beverages' },
  { name: 'Zitronensaftkonzentrat', category: 'beverages' },
  { name: 'Limettensaft', category: 'beverages' },
  { name: 'Tomatensaft', category: 'beverages' },
  { name: 'Bier', category: 'beverages' },
  { name: 'Alkoholfreies Bier', category: 'beverages' },
  { name: 'Rotwein', category: 'beverages' },
  { name: 'Weißwein', category: 'beverages' },
  { name: 'Sekt', category: 'beverages' },
  { name: 'Aperol', category: 'beverages' },
  { name: 'Cola', category: 'beverages' },
  { name: 'Fanta', category: 'beverages' },
  { name: 'Sprite', category: 'beverages' },
  { name: 'Eistee', category: 'beverages' },
  { name: 'Kaffee', category: 'beverages' },

  // Tiefkühl
  { name: 'Erbsen TK', category: 'frozen' },
  { name: 'Spinat TK', category: 'frozen' },
  { name: 'Beeren TK', category: 'frozen' },
  { name: 'Brokkoli TK', category: 'frozen' },
  { name: 'Gemüse TK', category: 'frozen' },
  { name: 'Mais TK', category: 'frozen' },
  { name: 'Kartoffeln TK', category: 'frozen' },
  { name: 'Blätterteig TK', category: 'frozen' },
  { name: 'Pizza TK', category: 'frozen' },

  // Vorratsschrank
  { name: 'Dosentomaten', category: 'pantry' },
  { name: 'Tomaten (ganz) aus der Dose', category: 'pantry' },
  { name: 'Tomatenstücke aus der Dose', category: 'pantry' },
  { name: 'Passata', category: 'pantry' },
  { name: 'Tomatenmark', category: 'pantry' },
  { name: 'Tomatensauce', category: 'pantry' },
  { name: 'Pizzasauce', category: 'pantry' },
  { name: 'Kichererbsen aus der Dose', category: 'pantry' },
  { name: 'Bohnen aus der Dose', category: 'pantry' },
  { name: 'Kokosmilch', category: 'pantry' },
  { name: 'Gemüsebrühe', category: 'pantry' },
  { name: 'Hühnerbrühe', category: 'pantry' },
  { name: 'Bratensauce', category: 'pantry' },
  { name: 'Tahini', category: 'pantry' },
  { name: 'Thunfisch', category: 'pantry' },
  { name: 'Honig', category: 'pantry' },
  { name: 'Marmelade', category: 'pantry' },
  { name: 'Konfitüre', category: 'pantry' },
  { name: 'Sirup', category: 'pantry' },
  { name: 'Ahornsirup', category: 'pantry' },
  { name: 'Agavendicksaft', category: 'pantry' },
  { name: 'Nüsse', category: 'pantry' },
  { name: 'Mandeln', category: 'pantry' },
  { name: 'Walnüsse', category: 'pantry' },
  { name: 'Haselnüsse', category: 'pantry' },
  { name: 'Cashews', category: 'pantry' },
  { name: 'Pistazien', category: 'pantry' },
  { name: 'Chiasamen', category: 'pantry' },
  { name: 'Leinsamen', category: 'pantry' },
  { name: 'Sonnenblumenkerne', category: 'pantry' },
  { name: 'Kürbiskerne', category: 'pantry' },
  { name: 'Rosinen', category: 'pantry' },
  { name: 'Cranberries', category: 'pantry' },
  { name: 'Datteln', category: 'pantry' },
  { name: 'Paniermehl', category: 'pantry' },
  { name: 'Semmelbrösel', category: 'pantry' },
  { name: 'Hafermilch', category: 'pantry' },
  { name: 'Sojamilch', category: 'pantry' },
  { name: 'Mandelmilch', category: 'pantry' },
  { name: 'Pflanzliche Sahne', category: 'pantry' },
  { name: 'Brot', category: 'pantry' },
  { name: 'Vollkornbrot', category: 'pantry' },
  { name: 'Toast', category: 'pantry' },
  { name: 'Toasties', category: 'pantry' },
  { name: 'English Muffins', category: 'pantry' },
  { name: 'Bagels', category: 'pantry' },
  { name: 'Brötchen', category: 'pantry' },
  { name: 'Baguette', category: 'pantry' },
  { name: 'Croissants', category: 'pantry' },
  { name: 'Müsli', category: 'pantry' },
  { name: 'Cornflakes', category: 'pantry' },

  // Haushalt / Nicht-Lebensmittel
  { name: 'Klopapier', category: 'other' },
  { name: 'Küchenrolle', category: 'other' },
  { name: 'Spülmittel', category: 'other' },
  { name: 'Spülmaschinen Tabs', category: 'other' },
  { name: 'Alufolie', category: 'other' },
  { name: 'Backpapier', category: 'other' },
  { name: 'Frischhaltefolie', category: 'other' },
  { name: 'Gefrierbeutel', category: 'other' },
  { name: 'Zahnpasta', category: 'other' },
  { name: 'Schwämme', category: 'other' },
  { name: 'Müllbeutel', category: 'other' },
  { name: 'Servietten', category: 'other' },
]
